In [114]:
print("hello world, this is numpy")

hello world, this is numpy


# Intro to Numpy

In [115]:
import numpy as np
import numpy.linalg as LA

In [116]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [117]:
print(type(b))
print(b.ndim)
print(b.shape)
print(b.size)

<class 'numpy.ndarray'>
2
(2, 3)
6


In [118]:
one_dim = np.array([1,2,3])
two_dim = np.array([[1,2,3]])

print(one_dim.shape)
print(two_dim.shape)

(3,)
(1, 3)


In [119]:
a[0] = 5
print(a)


[5 2 3 4]


In [120]:
a = np.zeros((2,2))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2),7)
print(c)
d = np.eye(2) #identity matrix
print(d)
e = np.arange(10,20,2) #start at 10, go upto 19, take steps of two 
print(e)

f = np.linspace(1,10,20)#print 20 equally spaced points between 1 and 10 
print(f)

g = np.zeros((3,4,5)) #4*5 matrix, three of them stacked together
print(g)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[10 12 14 16 18]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [121]:
a = np.arange(1,13).reshape((3,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [122]:
print(a[1])

[5 6 7 8]


In [123]:
print(a[1,1])

6


In [124]:
print(a[1][1])

6


In [125]:
print(a[:,1])

[ 2  6 10]


In [126]:
print(a[:][1])

[5 6 7 8]


In [127]:
for row in a: 
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [128]:
for item in a.flatten():
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [129]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [130]:
a = np.array([[2,1],[6,3]])
print(a)

[[2 1]
 [6 3]]


In [131]:
print(a.T)
print(np.transpose(a))

[[2 6]
 [1 3]]
[[2 6]
 [1 3]]


In [141]:
print(LA.inv(a))

[[-9.00719925e+15  3.00239975e+15]
 [ 1.80143985e+16 -6.00479950e+15]]


In [133]:
b = np.array([[-3,2],[-5,4]])
print(a+b)
print(a*b)
print(a/b)

[[-1  3]
 [ 1  7]]
[[ -6   2]
 [-30  12]]
[[-0.66666667  0.5       ]
 [-1.2         0.75      ]]


In [134]:
print(a.dot(b))
print(np.dot(a,b))

[[-11   8]
 [-33  24]]
[[-11   8]
 [-33  24]]


In [135]:
print(np.max(a))
print(np.max(a,axis=0))

6
[6 3]


In [136]:
print(np.sum(a))
print(np.sum(a,axis=0))

12
[8 4]


In [137]:
print(np.mean(a, axis=1))
print(np.std(a))

[1.5 4.5]
1.8708286933869707


In [138]:
w,v = LA.eig(a)

In [139]:
print(w)
print(v)

[0. 5.]
[[-0.4472136  -0.31622777]
 [ 0.89442719 -0.9486833 ]]


In [145]:
print(np.random.rand(4,3))

[[0.66625147 0.32413989 0.38851585]
 [0.12915105 0.30825053 0.52236073]
 [0.13266518 0.92133747 0.60183823]
 [0.38930393 0.00714813 0.94582725]]


In [147]:
print(np.random.randint(low=1,high=11,size=10))

[10  9  4  8 10  7  5  8 10 10]


In [148]:
print(np.random.randn(5,4)) #print numbers from a normal distribution

[[-0.0295444  -1.80116599 -0.03922771 -0.05910236]
 [ 1.43232004 -0.26227877 -1.6480345   0.59048389]
 [-0.16447114  0.29542468  0.47080491 -1.45156213]
 [ 0.47588183  0.15682967 -0.42535697  0.49233219]
 [ 0.96678097  0.97279296 -0.10432943 -0.02173312]]


In [151]:
#print numbers from a random distribution such as N(5,4)

print(5+2*np.random.randn(5,4))

[[6.40970387 8.40744125 6.33379319 2.38220164]
 [7.74152696 4.63307191 7.43284952 2.72242271]
 [2.70724653 4.43001939 3.64806538 4.7367686 ]
 [5.23817962 5.9894025  9.06686818 2.57004963]
 [5.42257923 4.57785396 6.98371007 6.50723934]]
