In [1]:
print("hello world, this is numpy")

hello world, this is numpy


# Intro to Numpy

In [2]:
import numpy as np
import numpy.linalg as LA

In [3]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [6]:
print(type(b))
print(b.ndim)
print(b.shape)
print(b.size)

<class 'numpy.ndarray'>
2
(2, 3)
6


In [7]:
one_dim = np.array([1,2,3])
two_dim = np.array([[1,2,3]])

print(one_dim.shape)
print(two_dim.shape)

(3,)
(1, 3)


In [8]:
a[0] = 5
print(a)


[5 2 3 4]


In [9]:
a = np.zeros((2,2))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2),7)
print(c)
d = np.eye(2) #identity matrix
print(d)
e = np.arange(10,20,2) #start at 10, go upto 19, take steps of two 
print(e)

f = np.linspace(1,10,20)#print 20 equally spaced points between 1 and 10 
print(f)

g = np.zeros((3,4,5)) #4*5 matrix, three of them stacked together
print(g)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[10 12 14 16 18]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [10]:
a = np.arange(1,13).reshape((3,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(a[1])

[5 6 7 8]


In [12]:
print(a[1,1])

6


In [13]:
print(a[1][1])

6


In [14]:
print(a[:,1])

[ 2  6 10]


In [15]:
print(a[:][1])

[5 6 7 8]


In [16]:
for row in a: 
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [17]:
for item in a.flatten():
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [18]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
a = np.array([[2,1],[6,3]])
print(a)

[[2 1]
 [6 3]]


In [20]:
print(a.T)
print(np.transpose(a))

[[2 6]
 [1 3]]
[[2 6]
 [1 3]]


In [21]:
print(LA.inv(a))

[[-9.00719925e+15  3.00239975e+15]
 [ 1.80143985e+16 -6.00479950e+15]]


In [22]:
b = np.array([[-3,2],[-5,4]])
print(a+b)
print(a*b)
print(a/b)

[[-1  3]
 [ 1  7]]
[[ -6   2]
 [-30  12]]
[[-0.66666667  0.5       ]
 [-1.2         0.75      ]]


In [23]:
print(a.dot(b))
print(np.dot(a,b))

[[-11   8]
 [-33  24]]
[[-11   8]
 [-33  24]]


In [24]:
print(np.max(a))
print(np.max(a,axis=0))

6
[6 3]


In [25]:
print(np.sum(a))
print(np.sum(a,axis=0))

12
[8 4]


In [26]:
print(np.mean(a, axis=1))
print(np.std(a))

[1.5 4.5]
1.8708286933869707


In [27]:
w,v = LA.eig(a)

In [28]:
print(w)
print(v)

[0. 5.]
[[-0.4472136  -0.31622777]
 [ 0.89442719 -0.9486833 ]]


In [29]:
print(np.random.rand(4,3))

[[0.47813718 0.34450437 0.90090039]
 [0.99487525 0.87350205 0.50210728]
 [0.68694604 0.0665664  0.58332498]
 [0.94956514 0.51089348 0.63756939]]


In [30]:
print(np.random.randint(low=1,high=11,size=10))

[ 6  4 10  7  6  3  1  5  4  7]


In [31]:
print(np.random.randn(5,4)) #print numbers from a normal distribution

[[ 1.91766342 -0.88116746 -0.07671108 -0.99111978]
 [-0.70011213  0.72792699  0.10271643  0.97950342]
 [ 0.03239785 -0.70519251 -0.26259029  0.67604239]
 [ 0.38252367 -0.1645054   0.42966513 -0.02261772]
 [ 0.33779962  1.01053661  0.26642744  1.10398209]]


In [32]:
#print numbers from a random distribution such as N(5,4)

print(5+2*np.random.randn(5,4))

[[2.58941211 3.03410997 2.51162493 6.30683885]
 [3.71758308 8.33425599 6.174142   3.97755049]
 [6.82615726 6.90232717 3.04075941 3.78941066]
 [1.30592509 2.48729896 5.18869815 4.19220078]
 [9.92392169 4.87498621 2.90171706 4.01418572]]


In [33]:
a = np.ones((8,8))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [34]:
a = a.reshape((8,-1))

In [35]:
a = a.flatten()
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [40]:
a = a.reshape(-1,8)
print(a)


ValueError: cannot reshape array of size 12 into shape (8)

In [42]:
a = np.array([[[1,2],[3,4]],
            [[5,6],[7,8]],
            [[9,10],[11,12]]])
print(a)
print(a.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


Let A and B be matrices. They have to be of the same dimension if they need to be added. In Numpy if you have a matrix and you try to add it to another matrix, say a scalar, then it tries to add it anyways by using broadcasting. For example, if you have [2 1 -3 -5] + [5], then numpy converts that to [5,5,5,5] and tries to add it to [2 1 3 5]


In [59]:
a  = np.array([[2,1],[-3,5]])
b = np.array([-4,7])
print(a+b)

[[-2  8]
 [-7 12]]


In [60]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print(np.vstack((a,b))) #vertical stacking

[[1 2 3]
 [4 5 6]]


In [61]:
print(np.hstack((a,b))) # horizontal stacking

[1 2 3 4 5 6]


In [62]:
a = np.array([1,2,3,4])
b = a
c = b 

a[0] =5
print(a)
print(b)

[5 2 3 4]
[5 2 3 4]


In [57]:
b = a.copy() #deep copy in numpy
print(b)

[5 7 3 4]


In [58]:
a[1] = 7
print(a)
print(b)

[5 7 3 4]
[5 7 3 4]
