In [1]:
import torch

In [2]:
x = torch.Tensor([5]) #this is numpy array with some pytorch functionality. 

In [3]:
x
x.requires_grad = True #this is telling pytorch that

In [4]:
x.shape

torch.Size([1])

In [5]:
y = x ** 2

In [6]:
#x.requires_grad

In [7]:
y.backward() #you have a computation graph loss.backward() computes dloss/dx for every parameter 
            # x which has requires_grad=True. These are accumulated into x.grad for every parameter x.


In [8]:
x.grad

tensor([10.])

In [9]:
x.data -= x.grad * 0.01

In [10]:
x.data

tensor([4.9000])

In [11]:
x1 = torch.Tensor([100]) #data point, which is the size of your room, this is a single data point 
w = torch.Tensor([1]) 
w.requires_grad = True
y = torch.Tensor([300])

In [12]:
y_pred = w*x1
y_pred

tensor([100.], grad_fn=<ThMulBackward>)

In [13]:
mse_loss = (y_pred -y)**2
mse_loss.backward()

In [14]:
w.grad

tensor([-40000.])